version: '3'

services:
  test-app:
    build: .
    ports:
      - "8080:8080"
    links:
      - "redis:redis"
    environment:
      - redis.uri=redis://redis

  redis:
    image: 'redis:6.2'
    hostname: redis
    ports:
      - "6378:6379"
#    volumes:
